# Generated by Django 5.0.2 on 2024-05-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_category_product2_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product2',
            new_name='Product',
        ),
    ]
