# Generated by Django 5.0.2 on 2024-05-21 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_rename_product2_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
