# Generated by Django 5.0.2 on 2024-05-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_productclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
